image:
  - Visual Studio 2017

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

install:
  - git submodule update --init

clone_folder: c:\projects\polymorphic_value

before_build:
  - cd c:\projects\polymorphic_value
  
build_script:
  - python scripts\build.py

test_script:
  - cd build
  - ctest . --output-on-failure -C "%CONFIGURATION%"